---

server:
  port: 8080
  servlet:
    contextPath: /
    session:
      timeout: 24h
      cookie:
        max-age: 24h

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  profiles:
    active: sample
  application:
    name: sample
    version: 1.2.0_SNAPSHOT

logging:
  level:
    org:
      springframework:
        security: DEBUG  # 本番時には必要であれば変更
    root: DEBUG  # 本番時には必要であれば変更

app:
  buildVersion: "@buildVersion@"
  package: com.example.app
  mainClass: Application
  i18n:
    encoding: UTF-8
    basename: i18n/messages